# Ethereum host connection info.
[ethereum]
URL = "ws://ropsten.dnp.dappnode.eth:8546/"
URLRPC = "http://ropsten.dnp.dappnode.eth:8545/"

# Keep operator Ethereum account.
[ethereum.account]
Address = ""
KeyFile = "/mnt/keystore/keep_wallet.json"

# Keep contract addresses configuration.
[ethereum.ContractAddresses]
KeepRandomBeaconOperator = "0x440626169759ad6598cd53558F0982b84A28Ad7a"
TokenStaking = "0xEb2bA3f065081B6459A6784ba8b34A1DfeCc183A"
KeepRandomBeaconService = "0xF9AEdd99357514d9D1AE389A65a4bd270cBCb56c"

# Keep network configuration.
[LibP2P]
Peers = [
  "/dns4/bootstrap-1.core.keep.test.boar.network/tcp/3001/ipfs/16Uiu2HAkuTUKNh6HkfvWBEkftZbqZHPHi3Kak5ZUygAxvsdQ2UgG",
  "/dns4/bootstrap-2.core.keep.test.boar.network/tcp/3001/ipfs/16Uiu2HAmQirGruZBvtbLHr5SDebsYGcq6Djw7ijF3gnkqsdQs3wK"
]
Port = 3919

# Storage is encrypted
[Storage]
DataDir = "/mnt/persistence"
