# Ethereum host connection info.
[ethereum]
URL = "ws://ropsten.dnp.dappnode.eth:8546/"
URLRPC = "http://ropsten.dnp.dappnode.eth:8545/"

# Keep operator Ethereum account.
[ethereum.account]
Address = "0x4748afff195f87ca25654deb5b2abd57547c284a"
KeyFile = "/mnt/keystore/keep_wallet.json"

# Keep contract addresses configuration.
[ethereum.ContractAddresses]
KeepRandomBeaconOperator = "0x440626169759ad6598cd53558F0982b84A28Ad7a"
TokenStaking = "0xEb2bA3f065081B6459A6784ba8b34A1DfeCc183A"
KeepRandomBeaconService = "0xF9AEdd99357514d9D1AE389A65a4bd270cBCb56c"

# Keep network configuration.
[LibP2P]
Peers = [
  "/dns4/bootstrap-0.test.keep.network/tcp/3919/ipfs/16Uiu2HAmCcfVpHwfBKNFbQuhvGuFXHVLQ65gB4sJm7HyrcZuLttH",
  "/dns4/bootstrap-1.test.keep.network/tcp/3919/ipfs/16Uiu2HAm3eJtyFKAttzJ85NLMromHuRg4yyum3CREMf6CHBBV6KY",
  "/dns4/testnet.keep-client.hashd.dev/tcp/3919/ipfs/16Uiu2HAmJsBiNVFNxsJ27NSQEByv39B1M7AKx5FrAc1htqYhHGhU",
  "/dns4/testnet2.keep-client.hashd.dev/tcp/3919/ipfs/16Uiu2HAmAV3sNGXTpdZCguUEd5QqMmg13WZ5dBTtjbhYeQmTHwgM"
]
Port = 3919

# Storage is encrypted
[Storage]
DataDir = "/mnt/persistence"
